freebsd_instance:
  image_family: freebsd-14-0

task:
  skip: $CIRRUS_BRANCH == 'pre-commit/.*'
  install_script: |
    pkg install -y cmake libzmq4 ninja git
  build_script: |
    mkdir build && cd build
    cmake -GNinja -DHELICS_BUILD_TESTS=ON -DHELICS_BUILD_EXAMPLES=ON -DCMAKE_CXX_STANDARD=17 ..
    cmake --build .
  test_script: |
    cd build
    ctest --output-on-failure --timeout 480 -C Release -L "SystemCI"
