codecov:
  notify:
    require_ci_to_pass: no
  branch: develop

coverage:
  precision: 2
  round: down
  range: "50...95"
  tests:
    target: 100%
    paths: "src/helics/shared_api_library/"
  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no

ignore:
  - "ThirdParty"
  - "examples"
  - "tests"
  - "interfaces"
  - "src/helics/core/mpi"
  - "**/logger.*"
  - "**/loggerCore.*"
  - "**/zmqHelper.*"
  - "**/internal/api_objects.h"
