---
engines:
  rubocop:
    enabled: true
  duplication:
    enabled: true
  metrics:
    enabled: true
  coverage:
    enabled: false
languages:

exclude_paths:
  - 'ThirdParty/**/*'
  - 'ThirdParty/*'
  - 'config/cmake/test_compiler_cxx/**'
  - 'interfaces/**/*'
  - 'scripts/**/*'
  - 'scripts/*'
  - 'tests/csharp/*'
  - '**.md'
