codecov:
  notify:
    require_ci_to_pass: no
    wait_for_ci: no
  branch: develop

coverage:
  precision: 2
  round: down
  range: '50...97'
  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: 'header, diff'
  behavior: default
  require_changes: no

ignore:
  - 'ThirdParty'
  - 'examples'
  - 'tests'
  - 'interfaces'
  - 'src/helics/core/mpi'
  - '**/logger.*'
  - '**/loggerCore.*'
  - '**/zmqHelper.*'
  - 'src/helics/shared_api_library/internal/api_objects.h'
