'\" t
.\"     Title: helics_app-player
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 03/06/2020
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "HELICS_APP\-PLAYER" "1" "03/06/2020" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
helics_app-player \- replays data from an input file into a federation
.SH "SYNOPSIS"
.sp
.nf
\fIhelics_app player\fR [\-v|\-\-version] [\-h|\-?|\-\-help]
    [\-\-quiet] [\-\-config\-file <file>] [\-\-local]
    [\-\-stop <time>] [\-\-input <file>]
    [\-\-marker <seconds>] [\-\-datatype <type>]
    [\-\-time_units <unit>]
    <input>
.fi
.SH "DESCRIPTION"
.sp
The player application provides an easy way to generate data in a federation by using recorded values from an input file\&.
.SH "OPTIONS"
.PP
\-\-marker <seconds>
.RS 4
Print a statement indicating time advancement during the simulation at the interval given by the argument (in seconds)\&.
.RE
.PP
\-\-datatype <type>
.RS 4
The data type to use for the publication\&.
.RE
.PP
\-\-time_units <unit>
.RS 4
The default units on the timestamps used for file based input\&. The default unit for timestamps is seconds\&.
.RE
.PP
<input>, \-\-input
.RS 4
The primary input file\&.
.RE
.PP
\-v, \-\-version
.RS 4
Prints the HELICS version used\&.
.RE
.PP
\-h, \-?, \-\-help
.RS 4
Prints usage, options, and available subcommands\&.
.RE
.PP
\-\-config\-file <file>
.RS 4
The base command line argument configuration file\&. A file named helics_config\&.ini is the default\&.
.RE
.PP
\-\-quiet
.RS 4
Silence most printed output\&.
.RE
.PP
\-\-local
.RS 4
Specify otherwise unspecified endpoints and publications as local\&. The publication and endpoint names will be prepended the player name\&.
.RE
.PP
\-\-stop <time>
.RS 4
The time to stop the app\&.
.RE
.SS "Federate Info"
.PP
\-n, \-\-name <name>
.RS 4
Name of the federate\&.
.RE
.PP
\-\-corename <name>
.RS 4
The name of the core to create or find\&.
.RE
.PP
\-i, \-\-coreinit, \-\-coreinitstring <init str>
.RS 4
The initialization arguments for the core\&.
.RE
.PP
\-\-brokerinit, \-\-brokerinitstring <init str>
.RS 4
The initialization arguments for the broker if autogenerated\&.
.RE
.PP
\-\-broker, \-\-brokeraddress <address>
.RS 4
Address or name of the broker to connect to\&.
.RE
.PP
\-\-brokerport <num>
.RS 4
Port number of the broker\&.
.RE
.PP
\-\-port <num>
.RS 4
Specify the port number to use\&.
.RE
.PP
\-\-localport <num>
.RS 4
Port number to use for connections to this federate\&.
.RE
.PP
\-\-autobroker
.RS 4
Automatically generate a broker if needed\&.
.RE
.PP
\-\-key, \-\-broker_key <key>
.RS 4
Specify a key to use to verify all connections to/from a broker\&.
.RE
.PP
\-\-offset <time>
.RS 4
The offset of the time steps (default in ms)\&.
.RE
.PP
\-\-period <time>
.RS 4
The execution cycle time of the federate (default in ms)\&.
.RE
.PP
\-\-timedelta <time>
.RS 4
The minimum time between time grants for a federate (default in ms)\&.
.RE
.PP
\-\-inputdelay <time>
.RS 4
The input delay on incoming communication of the federate (default in ms)\&.
.RE
.PP
\-\-outputdelay <time>
.RS 4
The output delay for outgoing communication of the federate (default in in ms)\&.
.RE
.PP
\-\-maxiterations <num>
.RS 4
The maximum number of iterations a federate is allowed to take\&.
.RE
.PP
\-\-loglevel <level>
.RS 4
The level at which to log messages; higher values result in more detailed logging\&. Use \-1 for no logging\&. Named levels are connections(3), data(6), error(0), interfaces(4), no_print(\-1), none(\-1), summary(2), timing(5), trace(7), and warning(1)\&.
.RE
.PP
\-\-separator <char>
.RS 4
Separator character for local federates\&. Default is
\fI/\fR\&.
.RE
.PP
\-f, \-\-flag, \-\-flags <flag>
.RS 4
Named flag for the federate\&. Argument can be used multiple times\&.
.RE
.PP
\-t, \-\-type, \-\-core, \-\-coretype
.RS 4
The type of core to connect to\&. Options include zmq (default), zmqss, tcp, tcpss, udp, mpi, and test\&.
.RE
.PP
\-\-rtlag <time>
.RS 4
The amount of time the federate is allowed to lag realtime before corrective action is taken (default in ms)\&.
.RE
.PP
\-\-rtlead <time>
.RS 4
The amount of time the federate is allowed to lead realtime before corrective action is taken (default in ms)\&.
.RE
.PP
\-\-rttolerance <time>
.RS 4
The time tolerance of the real time mode (default in ms)\&.
.RE
