'\" t
.\"     Title: helics_broker-term
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 03/06/2020
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "HELICS_BROKER\-TERM" "1" "03/06/2020" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
helics_broker-term \- a broker with an interactive terminal window
.SH "SYNOPSIS"
.sp
.nf
\fIhelics_broker term\fR [\-h|\-?|\-\-help]
.fi
.SH "DESCRIPTION"
.sp
The helics_broker term subcommand starts a broker and opens a terminal window for interacting with the broker\&. Run help in the terminal window to get a list of commands\&.
.SH "OPTIONS"
.PP
\-h, \-?, \-\-help
.RS 4
Prints usage, options, and available subcommands\&.
.RE
.SH "SEE ALSO"
.sp
helics_broker(1)
