/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class helics_iteration_status {
  public final static helics_iteration_status next_step = new helics_iteration_status("next_step");
  public final static helics_iteration_status iteration_error = new helics_iteration_status("iteration_error");
  public final static helics_iteration_status iteration_halted = new helics_iteration_status("iteration_halted");
  public final static helics_iteration_status iterating = new helics_iteration_status("iterating");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static helics_iteration_status swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + helics_iteration_status.class + " with value " + swigValue);
  }

  private helics_iteration_status(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private helics_iteration_status(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private helics_iteration_status(String swigName, helics_iteration_status swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static helics_iteration_status[] swigValues = { next_step, iteration_error, iteration_halted, iterating };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

