/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class helics_filter_type_t {
  public final static helics_filter_type_t helics_custom_filter = new helics_filter_type_t("helics_custom_filter", helicsJNI.helics_custom_filter_get());
  public final static helics_filter_type_t helics_delay_filter = new helics_filter_type_t("helics_delay_filter", helicsJNI.helics_delay_filter_get());
  public final static helics_filter_type_t helics_randomDelay_filter = new helics_filter_type_t("helics_randomDelay_filter", helicsJNI.helics_randomDelay_filter_get());
  public final static helics_filter_type_t helics_randomDrop_filter = new helics_filter_type_t("helics_randomDrop_filter", helicsJNI.helics_randomDrop_filter_get());
  public final static helics_filter_type_t helics_reroute_filter = new helics_filter_type_t("helics_reroute_filter", helicsJNI.helics_reroute_filter_get());
  public final static helics_filter_type_t helics_clone_filter = new helics_filter_type_t("helics_clone_filter", helicsJNI.helics_clone_filter_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static helics_filter_type_t swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + helics_filter_type_t.class + " with value " + swigValue);
  }

  private helics_filter_type_t(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private helics_filter_type_t(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private helics_filter_type_t(String swigName, helics_filter_type_t swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static helics_filter_type_t[] swigValues = { helics_custom_filter, helics_delay_filter, helics_randomDelay_filter, helics_randomDrop_filter, helics_reroute_filter, helics_clone_filter };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

