/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.java.helics;

public final class helics_time_properties {
  public final static helics_time_properties helics_time_property_time_delta = new helics_time_properties("helics_time_property_time_delta", helicsJNI.helics_time_property_time_delta_get());
  public final static helics_time_properties helics_time_property_period = new helics_time_properties("helics_time_property_period", helicsJNI.helics_time_property_period_get());
  public final static helics_time_properties helics_time_property_offset = new helics_time_properties("helics_time_property_offset", helicsJNI.helics_time_property_offset_get());
  public final static helics_time_properties helics_time_property_rt_lag = new helics_time_properties("helics_time_property_rt_lag", helicsJNI.helics_time_property_rt_lag_get());
  public final static helics_time_properties helics_time_property_rt_lead = new helics_time_properties("helics_time_property_rt_lead", helicsJNI.helics_time_property_rt_lead_get());
  public final static helics_time_properties helics_time_property_rt_tolerance = new helics_time_properties("helics_time_property_rt_tolerance", helicsJNI.helics_time_property_rt_tolerance_get());
  public final static helics_time_properties helics_time_property_input_delay = new helics_time_properties("helics_time_property_input_delay", helicsJNI.helics_time_property_input_delay_get());
  public final static helics_time_properties helics_time_property_output_delay = new helics_time_properties("helics_time_property_output_delay", helicsJNI.helics_time_property_output_delay_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static helics_time_properties swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + helics_time_properties.class + " with value " + swigValue);
  }

  private helics_time_properties(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private helics_time_properties(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private helics_time_properties(String swigName, helics_time_properties swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static helics_time_properties[] swigValues = { helics_time_property_time_delta, helics_time_property_period, helics_time_property_offset, helics_time_property_rt_lag, helics_time_property_rt_lead, helics_time_property_rt_tolerance, helics_time_property_input_delay, helics_time_property_output_delay };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

