/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.java.helics;

/**
 *  enumeration of the multi_input operations
 */
public final class HelicsMultiInputModes {
  /**
   *  time and priority order the inputs from the core library
   */
  public final static HelicsMultiInputModes HELICS_MULTI_INPUT_NO_OP = new HelicsMultiInputModes("HELICS_MULTI_INPUT_NO_OP", helicsJNI.HELICS_MULTI_INPUT_NO_OP_get());
  /**
   *  vectorize the inputs either double vector or string vector
   */
  public final static HelicsMultiInputModes HELICS_MULTI_INPUT_VECTORIZE_OPERATION = new HelicsMultiInputModes("HELICS_MULTI_INPUT_VECTORIZE_OPERATION", helicsJNI.HELICS_MULTI_INPUT_VECTORIZE_OPERATION_get());
  /**
   *  all inputs are assumed to be boolean and all must be true to return true
   */
  public final static HelicsMultiInputModes HELICS_MULTI_INPUT_AND_OPERATION = new HelicsMultiInputModes("HELICS_MULTI_INPUT_AND_OPERATION", helicsJNI.HELICS_MULTI_INPUT_AND_OPERATION_get());
  /**
   *  all inputs are assumed to be boolean and at least one must be true to return<br>
   *                   true
   */
  public final static HelicsMultiInputModes HELICS_MULTI_INPUT_OR_OPERATION = new HelicsMultiInputModes("HELICS_MULTI_INPUT_OR_OPERATION", helicsJNI.HELICS_MULTI_INPUT_OR_OPERATION_get());
  /**
   *  sum all the inputs
   */
  public final static HelicsMultiInputModes HELICS_MULTI_INPUT_SUM_OPERATION = new HelicsMultiInputModes("HELICS_MULTI_INPUT_SUM_OPERATION", helicsJNI.HELICS_MULTI_INPUT_SUM_OPERATION_get());
  /**
   *  do a difference operation on the inputs, first-sum(rest)<br>
   *                for double input, vector diff for vector input
   */
  public final static HelicsMultiInputModes HELICS_MULTI_INPUT_DIFF_OPERATION = new HelicsMultiInputModes("HELICS_MULTI_INPUT_DIFF_OPERATION", helicsJNI.HELICS_MULTI_INPUT_DIFF_OPERATION_get());
  /**
   *  find the max of the inputs
   */
  public final static HelicsMultiInputModes HELICS_MULTI_INPUT_MAX_OPERATION = new HelicsMultiInputModes("HELICS_MULTI_INPUT_MAX_OPERATION", helicsJNI.HELICS_MULTI_INPUT_MAX_OPERATION_get());
  /**
   *  find the min of the inputs
   */
  public final static HelicsMultiInputModes HELICS_MULTI_INPUT_MIN_OPERATION = new HelicsMultiInputModes("HELICS_MULTI_INPUT_MIN_OPERATION", helicsJNI.HELICS_MULTI_INPUT_MIN_OPERATION_get());
  /**
   *  take the average of the inputs
   */
  public final static HelicsMultiInputModes HELICS_MULTI_INPUT_AVERAGE_OPERATION = new HelicsMultiInputModes("HELICS_MULTI_INPUT_AVERAGE_OPERATION", helicsJNI.HELICS_MULTI_INPUT_AVERAGE_OPERATION_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static HelicsMultiInputModes swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + HelicsMultiInputModes.class + " with value " + swigValue);
  }

  private HelicsMultiInputModes(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private HelicsMultiInputModes(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private HelicsMultiInputModes(String swigName, HelicsMultiInputModes swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static HelicsMultiInputModes[] swigValues = { HELICS_MULTI_INPUT_NO_OP, HELICS_MULTI_INPUT_VECTORIZE_OPERATION, HELICS_MULTI_INPUT_AND_OPERATION, HELICS_MULTI_INPUT_OR_OPERATION, HELICS_MULTI_INPUT_SUM_OPERATION, HELICS_MULTI_INPUT_DIFF_OPERATION, HELICS_MULTI_INPUT_MAX_OPERATION, HELICS_MULTI_INPUT_MIN_OPERATION, HELICS_MULTI_INPUT_AVERAGE_OPERATION };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

