/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.java.helics;

public interface helicsConstants {
  public final static double HELICS_BIG_NUMBER = helicsJNI.HELICS_BIG_NUMBER_get();
}
