/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.java.helics;

/**
 *  enumeration of general flags that can be used in federates/cores/brokers 
 */
public final class HelicsFlags {
  /**
   *  flag specifying that a federate, core, or broker may be slow to respond to pings<br>
   *                    If the federate goes offline there is no good way to detect it so use with<br>
   *                   caution
   */
  public final static HelicsFlags HELICS_FLAG_SLOW_RESPONDING = new HelicsFlags("HELICS_FLAG_SLOW_RESPONDING", helicsJNI.HELICS_FLAG_SLOW_RESPONDING_get());
  /**
   *  flag specifying the federate/core/broker is operating in a user debug mode so<br>
   *                deadlock timers and timeout are disabled this flag is a combination of<br>
   *                slow_responding and disabling of some timeouts
   */
  public final static HelicsFlags HELICS_FLAG_DEBUGGING = new HelicsFlags("HELICS_FLAG_DEBUGGING", helicsJNI.HELICS_FLAG_DEBUGGING_get());
  /**
   *  specify that a federate error should terminate the federation
   */
  public final static HelicsFlags HELICS_FLAG_TERMINATE_ON_ERROR = new HelicsFlags("HELICS_FLAG_TERMINATE_ON_ERROR", helicsJNI.HELICS_FLAG_TERMINATE_ON_ERROR_get());
  /**
   *  specify that the log files should be flushed on every log message
   */
  public final static HelicsFlags HELICS_FLAG_FORCE_LOGGING_FLUSH = new HelicsFlags("HELICS_FLAG_FORCE_LOGGING_FLUSH", helicsJNI.HELICS_FLAG_FORCE_LOGGING_FLUSH_get());
  /**
   *  specify that a full log should be dumped into a file
   */
  public final static HelicsFlags HELICS_FLAG_DUMPLOG = new HelicsFlags("HELICS_FLAG_DUMPLOG", helicsJNI.HELICS_FLAG_DUMPLOG_get());
  /**
   *  specify that helics should capture profiling data
   */
  public final static HelicsFlags HELICS_FLAG_PROFILING = new HelicsFlags("HELICS_FLAG_PROFILING", helicsJNI.HELICS_FLAG_PROFILING_get());
  /**
   *  flag trigger for generating a profiling marker
   */
  public final static HelicsFlags HELICS_FLAG_PROFILING_MARKER = new HelicsFlags("HELICS_FLAG_PROFILING_MARKER", helicsJNI.HELICS_FLAG_PROFILING_MARKER_get());
  /**
   *  specify that the federate/core/broker should allow some remote control operations<br>
   *                   such as finalize
   */
  public final static HelicsFlags HELICS_FLAG_ALLOW_REMOTE_CONTROL = new HelicsFlags("HELICS_FLAG_ALLOW_REMOTE_CONTROL", helicsJNI.HELICS_FLAG_ALLOW_REMOTE_CONTROL_get());
  /**
   *  specify that the federate/core/broker should *NOT* allow some remote control<br>
   *                   operations such as finalize
   */
  public final static HelicsFlags HELICS_FLAG_DISABLE_REMOTE_CONTROL = new HelicsFlags("HELICS_FLAG_DISABLE_REMOTE_CONTROL", helicsJNI.HELICS_FLAG_DISABLE_REMOTE_CONTROL_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static HelicsFlags swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + HelicsFlags.class + " with value " + swigValue);
  }

  private HelicsFlags(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private HelicsFlags(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private HelicsFlags(String swigName, HelicsFlags swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static HelicsFlags[] swigValues = { HELICS_FLAG_SLOW_RESPONDING, HELICS_FLAG_DEBUGGING, HELICS_FLAG_TERMINATE_ON_ERROR, HELICS_FLAG_FORCE_LOGGING_FLUSH, HELICS_FLAG_DUMPLOG, HELICS_FLAG_PROFILING, HELICS_FLAG_PROFILING_MARKER, HELICS_FLAG_ALLOW_REMOTE_CONTROL, HELICS_FLAG_DISABLE_REMOTE_CONTROL };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

