/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.java.helics;

public interface helicsConstants {
  public final static double HELICS_BIG_NUMBER = helicsJNI.HELICS_BIG_NUMBER_get();
  public final static double HELICS_INVALID_DOUBLE = helicsJNI.HELICS_INVALID_DOUBLE_get();
}
