/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.java.helics;

public final class HelicsFilterTypes {
  public final static HelicsFilterTypes HELICS_FILTER_TYPE_CUSTOM = new HelicsFilterTypes("HELICS_FILTER_TYPE_CUSTOM", helicsJNI.HELICS_FILTER_TYPE_CUSTOM_get());
  public final static HelicsFilterTypes HELICS_FILTER_TYPE_DELAY = new HelicsFilterTypes("HELICS_FILTER_TYPE_DELAY", helicsJNI.HELICS_FILTER_TYPE_DELAY_get());
  public final static HelicsFilterTypes HELICS_FILTER_TYPE_RANDOM_DELAY = new HelicsFilterTypes("HELICS_FILTER_TYPE_RANDOM_DELAY", helicsJNI.HELICS_FILTER_TYPE_RANDOM_DELAY_get());
  public final static HelicsFilterTypes HELICS_FILTER_TYPE_RANDOM_DROP = new HelicsFilterTypes("HELICS_FILTER_TYPE_RANDOM_DROP", helicsJNI.HELICS_FILTER_TYPE_RANDOM_DROP_get());
  public final static HelicsFilterTypes HELICS_FILTER_TYPE_REROUTE = new HelicsFilterTypes("HELICS_FILTER_TYPE_REROUTE", helicsJNI.HELICS_FILTER_TYPE_REROUTE_get());
  public final static HelicsFilterTypes HELICS_FILTER_TYPE_CLONE = new HelicsFilterTypes("HELICS_FILTER_TYPE_CLONE", helicsJNI.HELICS_FILTER_TYPE_CLONE_get());
  public final static HelicsFilterTypes HELICS_FILTER_TYPE_FIREWALL = new HelicsFilterTypes("HELICS_FILTER_TYPE_FIREWALL", helicsJNI.HELICS_FILTER_TYPE_FIREWALL_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static HelicsFilterTypes swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + HelicsFilterTypes.class + " with value " + swigValue);
  }

  private HelicsFilterTypes(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private HelicsFilterTypes(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private HelicsFilterTypes(String swigName, HelicsFilterTypes swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static HelicsFilterTypes[] swigValues = { HELICS_FILTER_TYPE_CUSTOM, HELICS_FILTER_TYPE_DELAY, HELICS_FILTER_TYPE_RANDOM_DELAY, HELICS_FILTER_TYPE_RANDOM_DROP, HELICS_FILTER_TYPE_REROUTE, HELICS_FILTER_TYPE_CLONE, HELICS_FILTER_TYPE_FIREWALL };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

