/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.java.helics;

public final class helics_federate_state {
  public final static helics_federate_state helics_state_startup = new helics_federate_state("helics_state_startup", helicsJNI.helics_state_startup_get());
  public final static helics_federate_state helics_state_initialization = new helics_federate_state("helics_state_initialization");
  public final static helics_federate_state helics_state_execution = new helics_federate_state("helics_state_execution");
  public final static helics_federate_state helics_state_finalize = new helics_federate_state("helics_state_finalize");
  public final static helics_federate_state helics_state_error = new helics_federate_state("helics_state_error");
  public final static helics_federate_state helics_state_pending_init = new helics_federate_state("helics_state_pending_init");
  public final static helics_federate_state helics_state_pending_exec = new helics_federate_state("helics_state_pending_exec");
  public final static helics_federate_state helics_state_pending_time = new helics_federate_state("helics_state_pending_time");
  public final static helics_federate_state helics_state_pending_iterative_time = new helics_federate_state("helics_state_pending_iterative_time");
  public final static helics_federate_state helics_state_pending_finalize = new helics_federate_state("helics_state_pending_finalize");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static helics_federate_state swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + helics_federate_state.class + " with value " + swigValue);
  }

  private helics_federate_state(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private helics_federate_state(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private helics_federate_state(String swigName, helics_federate_state swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static helics_federate_state[] swigValues = { helics_state_startup, helics_state_initialization, helics_state_execution, helics_state_finalize, helics_state_error, helics_state_pending_init, helics_state_pending_exec, helics_state_pending_time, helics_state_pending_iterative_time, helics_state_pending_finalize };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

