/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.java.helics;

/**
 * enumeration of possible return values from an iterative time request
 */
public final class HelicsIterationResult {
  /**
   *  the iterations have progressed to the next time 
   */
  public final static HelicsIterationResult HELICS_ITERATION_RESULT_NEXT_STEP = new HelicsIterationResult("HELICS_ITERATION_RESULT_NEXT_STEP", helicsJNI.HELICS_ITERATION_RESULT_NEXT_STEP_get());
  /**
   *  there was an error 
   */
  public final static HelicsIterationResult HELICS_ITERATION_RESULT_ERROR = new HelicsIterationResult("HELICS_ITERATION_RESULT_ERROR", helicsJNI.HELICS_ITERATION_RESULT_ERROR_get());
  /**
   *  the federation has halted 
   */
  public final static HelicsIterationResult HELICS_ITERATION_RESULT_HALTED = new HelicsIterationResult("HELICS_ITERATION_RESULT_HALTED", helicsJNI.HELICS_ITERATION_RESULT_HALTED_get());
  /**
   *  the federate is iterating at current time 
   */
  public final static HelicsIterationResult HELICS_ITERATION_RESULT_ITERATING = new HelicsIterationResult("HELICS_ITERATION_RESULT_ITERATING", helicsJNI.HELICS_ITERATION_RESULT_ITERATING_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static HelicsIterationResult swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + HelicsIterationResult.class + " with value " + swigValue);
  }

  private HelicsIterationResult(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private HelicsIterationResult(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private HelicsIterationResult(String swigName, HelicsIterationResult swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static HelicsIterationResult[] swigValues = { HELICS_ITERATION_RESULT_NEXT_STEP, HELICS_ITERATION_RESULT_ERROR, HELICS_ITERATION_RESULT_HALTED, HELICS_ITERATION_RESULT_ITERATING };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

