/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.java.helics;

/**
 * enumeration of the different iteration results
 */
public final class HelicsIterationRequest {
  /**
   *  no iteration is requested 
   */
  public final static HelicsIterationRequest HELICS_ITERATION_REQUEST_NO_ITERATION = new HelicsIterationRequest("HELICS_ITERATION_REQUEST_NO_ITERATION", helicsJNI.HELICS_ITERATION_REQUEST_NO_ITERATION_get());
  /**
   *  force iteration return when able 
   */
  public final static HelicsIterationRequest HELICS_ITERATION_REQUEST_FORCE_ITERATION = new HelicsIterationRequest("HELICS_ITERATION_REQUEST_FORCE_ITERATION", helicsJNI.HELICS_ITERATION_REQUEST_FORCE_ITERATION_get());
  /**
   *  only return an iteration if necessary 
   */
  public final static HelicsIterationRequest HELICS_ITERATION_REQUEST_ITERATE_IF_NEEDED = new HelicsIterationRequest("HELICS_ITERATION_REQUEST_ITERATE_IF_NEEDED", helicsJNI.HELICS_ITERATION_REQUEST_ITERATE_IF_NEEDED_get());
  /**
   *  halt the federate
   */
  public final static HelicsIterationRequest HELICS_ITERATION_REQUEST_HALT_OPERATIONS = new HelicsIterationRequest("HELICS_ITERATION_REQUEST_HALT_OPERATIONS", helicsJNI.HELICS_ITERATION_REQUEST_HALT_OPERATIONS_get());
  /**
   *  indicate there was an error 
   */
  public final static HelicsIterationRequest HELICS_ITERATION_REQUEST_ERROR = new HelicsIterationRequest("HELICS_ITERATION_REQUEST_ERROR", helicsJNI.HELICS_ITERATION_REQUEST_ERROR_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static HelicsIterationRequest swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + HelicsIterationRequest.class + " with value " + swigValue);
  }

  private HelicsIterationRequest(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private HelicsIterationRequest(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private HelicsIterationRequest(String swigName, HelicsIterationRequest swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static HelicsIterationRequest[] swigValues = { HELICS_ITERATION_REQUEST_NO_ITERATION, HELICS_ITERATION_REQUEST_FORCE_ITERATION, HELICS_ITERATION_REQUEST_ITERATE_IF_NEEDED, HELICS_ITERATION_REQUEST_HALT_OPERATIONS, HELICS_ITERATION_REQUEST_ERROR };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

