/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.java.helics;

/**
 *  log level definitions
 */
public final class HelicsLogLevels {
  /**
   *  log level for dumping log messages
   */
  public final static HelicsLogLevels HELICS_LOG_LEVEL_DUMPLOG = new HelicsLogLevels("HELICS_LOG_LEVEL_DUMPLOG", helicsJNI.HELICS_LOG_LEVEL_DUMPLOG_get());
  /**
   *  don't print anything except a few catastrophic errors
   */
  public final static HelicsLogLevels HELICS_LOG_LEVEL_NO_PRINT = new HelicsLogLevels("HELICS_LOG_LEVEL_NO_PRINT", helicsJNI.HELICS_LOG_LEVEL_NO_PRINT_get());
  /**
   *  only print error level indicators
   */
  public final static HelicsLogLevels HELICS_LOG_LEVEL_ERROR = new HelicsLogLevels("HELICS_LOG_LEVEL_ERROR", helicsJNI.HELICS_LOG_LEVEL_ERROR_get());
  /**
   *  profiling log level
   */
  public final static HelicsLogLevels HELICS_LOG_LEVEL_PROFILING = new HelicsLogLevels("HELICS_LOG_LEVEL_PROFILING", helicsJNI.HELICS_LOG_LEVEL_PROFILING_get());
  /**
   *  only print warnings and errors
   */
  public final static HelicsLogLevels HELICS_LOG_LEVEL_WARNING = new HelicsLogLevels("HELICS_LOG_LEVEL_WARNING", helicsJNI.HELICS_LOG_LEVEL_WARNING_get());
  /**
   *  warning errors and summary level information
   */
  public final static HelicsLogLevels HELICS_LOG_LEVEL_SUMMARY = new HelicsLogLevels("HELICS_LOG_LEVEL_SUMMARY", helicsJNI.HELICS_LOG_LEVEL_SUMMARY_get());
  /**
   *  summary+ notices about federate and broker connections +messages about network<br>
   *                   connections
   */
  public final static HelicsLogLevels HELICS_LOG_LEVEL_CONNECTIONS = new HelicsLogLevels("HELICS_LOG_LEVEL_CONNECTIONS", helicsJNI.HELICS_LOG_LEVEL_CONNECTIONS_get());
  /**
   *  connections+ interface definitions
   */
  public final static HelicsLogLevels HELICS_LOG_LEVEL_INTERFACES = new HelicsLogLevels("HELICS_LOG_LEVEL_INTERFACES", helicsJNI.HELICS_LOG_LEVEL_INTERFACES_get());
  /**
   *  interfaces + timing message
   */
  public final static HelicsLogLevels HELICS_LOG_LEVEL_TIMING = new HelicsLogLevels("HELICS_LOG_LEVEL_TIMING", helicsJNI.HELICS_LOG_LEVEL_TIMING_get());
  /**
   *  timing+ data transfer notices
   */
  public final static HelicsLogLevels HELICS_LOG_LEVEL_DATA = new HelicsLogLevels("HELICS_LOG_LEVEL_DATA", helicsJNI.HELICS_LOG_LEVEL_DATA_get());
  /**
   *  data+ additional debug message
   */
  public final static HelicsLogLevels HELICS_LOG_LEVEL_DEBUG = new HelicsLogLevels("HELICS_LOG_LEVEL_DEBUG", helicsJNI.HELICS_LOG_LEVEL_DEBUG_get());
  /**
   *  all internal messages
   */
  public final static HelicsLogLevels HELICS_LOG_LEVEL_TRACE = new HelicsLogLevels("HELICS_LOG_LEVEL_TRACE", helicsJNI.HELICS_LOG_LEVEL_TRACE_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static HelicsLogLevels swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + HelicsLogLevels.class + " with value " + swigValue);
  }

  private HelicsLogLevels(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private HelicsLogLevels(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private HelicsLogLevels(String swigName, HelicsLogLevels swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static HelicsLogLevels[] swigValues = { HELICS_LOG_LEVEL_DUMPLOG, HELICS_LOG_LEVEL_NO_PRINT, HELICS_LOG_LEVEL_ERROR, HELICS_LOG_LEVEL_PROFILING, HELICS_LOG_LEVEL_WARNING, HELICS_LOG_LEVEL_SUMMARY, HELICS_LOG_LEVEL_CONNECTIONS, HELICS_LOG_LEVEL_INTERFACES, HELICS_LOG_LEVEL_TIMING, HELICS_LOG_LEVEL_DATA, HELICS_LOG_LEVEL_DEBUG, HELICS_LOG_LEVEL_TRACE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

