/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.java.helics;

public final class HelicsDataTypes {
  public final static HelicsDataTypes HELICS_DATA_TYPE_STRING = new HelicsDataTypes("HELICS_DATA_TYPE_STRING", helicsJNI.HELICS_DATA_TYPE_STRING_get());
  public final static HelicsDataTypes HELICS_DATA_TYPE_DOUBLE = new HelicsDataTypes("HELICS_DATA_TYPE_DOUBLE", helicsJNI.HELICS_DATA_TYPE_DOUBLE_get());
  public final static HelicsDataTypes HELICS_DATA_TYPE_INT = new HelicsDataTypes("HELICS_DATA_TYPE_INT", helicsJNI.HELICS_DATA_TYPE_INT_get());
  public final static HelicsDataTypes HELICS_DATA_TYPE_COMPLEX = new HelicsDataTypes("HELICS_DATA_TYPE_COMPLEX", helicsJNI.HELICS_DATA_TYPE_COMPLEX_get());
  public final static HelicsDataTypes HELICS_DATA_TYPE_VECTOR = new HelicsDataTypes("HELICS_DATA_TYPE_VECTOR", helicsJNI.HELICS_DATA_TYPE_VECTOR_get());
  public final static HelicsDataTypes HELICS_DATA_TYPE_COMPLEX_VECTOR = new HelicsDataTypes("HELICS_DATA_TYPE_COMPLEX_VECTOR", helicsJNI.HELICS_DATA_TYPE_COMPLEX_VECTOR_get());
  public final static HelicsDataTypes HELICS_DATA_TYPE_NAMED_POINT = new HelicsDataTypes("HELICS_DATA_TYPE_NAMED_POINT", helicsJNI.HELICS_DATA_TYPE_NAMED_POINT_get());
  public final static HelicsDataTypes HELICS_DATA_TYPE_BOOLEAN = new HelicsDataTypes("HELICS_DATA_TYPE_BOOLEAN", helicsJNI.HELICS_DATA_TYPE_BOOLEAN_get());
  public final static HelicsDataTypes HELICS_DATA_TYPE_TIME = new HelicsDataTypes("HELICS_DATA_TYPE_TIME", helicsJNI.HELICS_DATA_TYPE_TIME_get());
  public final static HelicsDataTypes HELICS_DATA_TYPE_RAW = new HelicsDataTypes("HELICS_DATA_TYPE_RAW", helicsJNI.HELICS_DATA_TYPE_RAW_get());
  public final static HelicsDataTypes HELICS_DATA_TYPE_MULTI = new HelicsDataTypes("HELICS_DATA_TYPE_MULTI", helicsJNI.HELICS_DATA_TYPE_MULTI_get());
  public final static HelicsDataTypes HELICS_DATA_TYPE_ANY = new HelicsDataTypes("HELICS_DATA_TYPE_ANY", helicsJNI.HELICS_DATA_TYPE_ANY_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static HelicsDataTypes swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + HelicsDataTypes.class + " with value " + swigValue);
  }

  private HelicsDataTypes(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private HelicsDataTypes(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private HelicsDataTypes(String swigName, HelicsDataTypes swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static HelicsDataTypes[] swigValues = { HELICS_DATA_TYPE_STRING, HELICS_DATA_TYPE_DOUBLE, HELICS_DATA_TYPE_INT, HELICS_DATA_TYPE_COMPLEX, HELICS_DATA_TYPE_VECTOR, HELICS_DATA_TYPE_COMPLEX_VECTOR, HELICS_DATA_TYPE_NAMED_POINT, HELICS_DATA_TYPE_BOOLEAN, HELICS_DATA_TYPE_TIME, HELICS_DATA_TYPE_RAW, HELICS_DATA_TYPE_MULTI, HELICS_DATA_TYPE_ANY };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

