/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.java.helics;

public final class HelicsErrorTypes {
  public final static HelicsErrorTypes HELICS_ERROR_FATAL = new HelicsErrorTypes("HELICS_ERROR_FATAL", helicsJNI.HELICS_ERROR_FATAL_get());
  public final static HelicsErrorTypes HELICS_ERROR_EXTERNAL_TYPE = new HelicsErrorTypes("HELICS_ERROR_EXTERNAL_TYPE", helicsJNI.HELICS_ERROR_EXTERNAL_TYPE_get());
  public final static HelicsErrorTypes HELICS_ERROR_OTHER = new HelicsErrorTypes("HELICS_ERROR_OTHER", helicsJNI.HELICS_ERROR_OTHER_get());
  public final static HelicsErrorTypes HELICS_ERROR_USER_ABORT = new HelicsErrorTypes("HELICS_ERROR_USER_ABORT", helicsJNI.HELICS_ERROR_USER_ABORT_get());
  public final static HelicsErrorTypes HELICS_ERROR_INSUFFICIENT_SPACE = new HelicsErrorTypes("HELICS_ERROR_INSUFFICIENT_SPACE", helicsJNI.HELICS_ERROR_INSUFFICIENT_SPACE_get());
  public final static HelicsErrorTypes HELICS_ERROR_EXECUTION_FAILURE = new HelicsErrorTypes("HELICS_ERROR_EXECUTION_FAILURE", helicsJNI.HELICS_ERROR_EXECUTION_FAILURE_get());
  public final static HelicsErrorTypes HELICS_ERROR_INVALID_FUNCTION_CALL = new HelicsErrorTypes("HELICS_ERROR_INVALID_FUNCTION_CALL", helicsJNI.HELICS_ERROR_INVALID_FUNCTION_CALL_get());
  public final static HelicsErrorTypes HELICS_ERROR_INVALID_STATE_TRANSITION = new HelicsErrorTypes("HELICS_ERROR_INVALID_STATE_TRANSITION", helicsJNI.HELICS_ERROR_INVALID_STATE_TRANSITION_get());
  public final static HelicsErrorTypes HELICS_WARNING = new HelicsErrorTypes("HELICS_WARNING", helicsJNI.HELICS_WARNING_get());
  public final static HelicsErrorTypes HELICS_ERROR_SYSTEM_FAILURE = new HelicsErrorTypes("HELICS_ERROR_SYSTEM_FAILURE", helicsJNI.HELICS_ERROR_SYSTEM_FAILURE_get());
  public final static HelicsErrorTypes HELICS_ERROR_DISCARD = new HelicsErrorTypes("HELICS_ERROR_DISCARD", helicsJNI.HELICS_ERROR_DISCARD_get());
  public final static HelicsErrorTypes HELICS_ERROR_INVALID_ARGUMENT = new HelicsErrorTypes("HELICS_ERROR_INVALID_ARGUMENT", helicsJNI.HELICS_ERROR_INVALID_ARGUMENT_get());
  public final static HelicsErrorTypes HELICS_ERROR_INVALID_OBJECT = new HelicsErrorTypes("HELICS_ERROR_INVALID_OBJECT", helicsJNI.HELICS_ERROR_INVALID_OBJECT_get());
  public final static HelicsErrorTypes HELICS_ERROR_CONNECTION_FAILURE = new HelicsErrorTypes("HELICS_ERROR_CONNECTION_FAILURE", helicsJNI.HELICS_ERROR_CONNECTION_FAILURE_get());
  public final static HelicsErrorTypes HELICS_ERROR_REGISTRATION_FAILURE = new HelicsErrorTypes("HELICS_ERROR_REGISTRATION_FAILURE", helicsJNI.HELICS_ERROR_REGISTRATION_FAILURE_get());
  public final static HelicsErrorTypes HELICS_OK = new HelicsErrorTypes("HELICS_OK", helicsJNI.HELICS_OK_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static HelicsErrorTypes swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + HelicsErrorTypes.class + " with value " + swigValue);
  }

  private HelicsErrorTypes(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private HelicsErrorTypes(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private HelicsErrorTypes(String swigName, HelicsErrorTypes swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static HelicsErrorTypes[] swigValues = { HELICS_ERROR_FATAL, HELICS_ERROR_EXTERNAL_TYPE, HELICS_ERROR_OTHER, HELICS_ERROR_USER_ABORT, HELICS_ERROR_INSUFFICIENT_SPACE, HELICS_ERROR_EXECUTION_FAILURE, HELICS_ERROR_INVALID_FUNCTION_CALL, HELICS_ERROR_INVALID_STATE_TRANSITION, HELICS_WARNING, HELICS_ERROR_SYSTEM_FAILURE, HELICS_ERROR_DISCARD, HELICS_ERROR_INVALID_ARGUMENT, HELICS_ERROR_INVALID_OBJECT, HELICS_ERROR_CONNECTION_FAILURE, HELICS_ERROR_REGISTRATION_FAILURE, HELICS_OK };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

