FROM ubuntu:18.04 as builder

RUN apt update && apt install -y \
  libboost-dev \
  libboost-test-dev \
  python3-dev \
  build-essential clang cmake git wget subversion vim

WORKDIR /root/develop

RUN svn co http://llvm.org/svn/llvm-project/llvm/trunk llvm
RUN (cd llvm/projects && svn co http://llvm.org/svn/llvm-project/libcxx/trunk libcxx)
RUN (cd llvm/projects && svn co http://llvm.org/svn/llvm-project/libcxxabi/trunk libcxxabi)

RUN  mkdir libcxx_msan && cd libcxx_msan &&  cmake ../llvm -DCMAKE_BUILD_TYPE=Release -DLLVM_USE_SANITIZER=Memory -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
RUN cd libcxx_msan && make cxx -j12
ENV MSAN_CFLAGS="-fsanitize=memory -stdlib=libc++ -L/root/develop/libcxx_msan/lib -lc++abi -I/root/develop/libcxx_msan/include -I/root/develop/libcxx_msan/include/c++/v1 -Wno-unused-command-line-argument -fno-omit-frame-pointer -g -O1 -Wl,-rpath=/root/develop/libcxx_msan/lib"

RUN rm -rf llvm
# Create script to build helics
RUN printf "#!/bin/bash \
\ngit clone https://github.com/GMLC-TDC/HELICS.git \
\ncd HELICS \
\nmkdir build \
\ncd build \
\ncmake .. -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_FLAGS=\"${MSAN_CFLAGS}\"  -DBUILD_HELICS_BOOST_TESTS=OFF -DZMQ_SUBPROJECT=ON  -DZMQ_FORCE_SUBPROJECT=ON \
\ncd /root/develop/HELICS/build \
\nmake -j  \
\n/root/develop/HELICS/build/tests/helics/core/core-tests \
\n/root/develop/HELICS/build/tests/helics/common/common-tests \
\n/root/develop/HELICS/build/tests/helics/system_tests/system-tests \
\n" > /root/develop/buildhelics.sh
RUN chmod 775 /root/develop/buildhelics.sh



ENV PYTHONPATH /usr/local/python

# Python must be installed after the PYTHONPATH is set above for it to
# recognize and import libhelicsSharedLib.so.
RUN apt install -y --no-install-recommends python3-dev \
  && rm -rf /var/lib/apt/lists/*

