FROM ubuntu:18.04 as builder

# Sets the number of threads for make to use
ARG MAKE_PARALLEL

RUN apt update && apt install -y \
  libboost-dev \
  libzmq5-dev \ 
  g++ \
  cmake git

WORKDIR /root/develop

RUN git clone https://github.com/GMLC-TDC/HELICS.git
RUN cd HELICS && mkdir build  && cd build && cmake .. -DBUILD_HELICS_TESTS=OFF
RUN cd HELICS && cd build && make -j${MAKE_PARALLEL:-2} install
# Create script to build helics

RUN rm -rf /var/lib/apt/lists/*
RUN rm -rf HELICS

