FROM ubuntu:19.04 as builder


RUN apt update && apt install -y \
  python3 \
  make clang cmake git wget subversion

WORKDIR /root/develop

RUN svn co http://llvm.org/svn/llvm-project/llvm/trunk llvm
RUN (cd llvm/projects && svn co http://llvm.org/svn/llvm-project/libcxx/trunk libcxx)
RUN (cd llvm/projects && svn co http://llvm.org/svn/llvm-project/libcxxabi/trunk libcxxabi)

# Sets the number of threads for make to use
ARG MAKE_PARALLEL

RUN  mkdir libcxx_msan_build && cd libcxx_msan_build &&  cmake ../llvm -DCMAKE_BUILD_TYPE=Release -DLLVM_USE_SANITIZER=Memory -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
RUN cd libcxx_msan_build && make cxx -j${MAKE_PARALLEL:-2}

RUN mkdir -p /root/develop/libcxx_msan/include && cp -r /root/develop/libcxx_msan_build/include/* /root/develop/libcxx_msan/include/
RUN mkdir -p /root/develop/libcxx_msan/lib && cp -r /root/develop/libcxx_msan_build/lib/* /root/develop/libcxx_msan/lib/

# Create final image with the build tools and the compiled libraries
FROM ubuntu:19.04

RUN apt update && apt install -y \
  libboost-dev \
  clang cmake make git && apt-get clean && ln -s /usr/bin/llvm-symbolizer-8 /usr/bin/llvm-symbolizer

#copy the built libraries from the builder images
COPY --from=builder /root/develop/libcxx_msan /root/develop/libcxx_msan

# Create script to build helics
RUN printf "#!/bin/bash \
\ngit clone https://github.com/GMLC-TDC/HELICS.git \
\ncd HELICS \
\nmkdir build \
\ncd build \
\ncmake .. -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_FLAGS=\"${MSAN_CFLAGS}\"  -DBUILD_HELICS_BOOST_TESTS=OFF -DZMQ_SUBPROJECT=ON  -DZMQ_FORCE_SUBPROJECT=ON \
\ncd /root/develop/HELICS/build \
\nmake -j${MAKE_PARALLEL:-2} \
\n/root/develop/HELICS/build/tests/helics/core/core-tests \
\n/root/develop/HELICS/build/tests/helics/common/common-tests \
\n/root/develop/HELICS/build/tests/helics/system_tests/system-tests \
\n" > /root/develop/buildhelics.sh


ENV MSAN_CFLAGS="-fsanitize=memory -stdlib=libc++ -L/root/develop/libcxx_msan/lib -lc++abi -I/root/develop/libcxx_msan/include -I/root/develop/libcxx_msan/include/c++/v1 -Wno-unused-command-line-argument -fno-omit-frame-pointer -g -O1 -Wl,-rpath=/root/develop/libcxx_msan/lib"


