FROM ubuntu:18.04 as builder

# Sets the number of threads for make to use
ARG MAKE_PARALLEL

RUN apt update && apt install -y \
  python3-dev \
  build-essential clang cmake git wget subversion vim && rm -rf /var/lib/apt/lists/*

WORKDIR /root/develop

RUN svn co http://llvm.org/svn/llvm-project/llvm/trunk llvm
RUN (cd llvm/projects && svn co http://llvm.org/svn/llvm-project/libcxx/trunk libcxx)
RUN (cd llvm/projects && svn co http://llvm.org/svn/llvm-project/libcxxabi/trunk libcxxabi)

RUN  mkdir libcxx_asan && cd libcxx_asan &&  cmake ../llvm -DCMAKE_BUILD_TYPE=Release -DLLVM_USE_SANITIZER=Address -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
RUN cd libcxx_asan && make cxx -j${MAKE_PARALLEL:-2}

COPY /root/develop/libcxx_asan/include /root/develop/libcxx/include
COPY /root/develop/libcxx_asan/lib /root/develop/libcxx/include

FROM ubuntu:18.04

COPY --from=builder /root/develop/libcxx /root/develop/libcxx
ENV ASAN_CFLAGS="-fsanitize=undefined,address -stdlib=libc++ -L/root/develop/libcxx/lib -lc++abi -I/root/develop/libcxx/include -I/root/develop/libcxx/include/c++/v1 -Wno-unused-command-line-argument -fno-omit-frame-pointer -g -O1 -Wl,-rpath=/root/develop/libcxx/lib"

RUN apt update && apt install -y \
  libboost-dev \
  clang cmake make git && rm -rf /var/lib/apt/lists/*

RUN rm -rf llvm
# Create script to build helics
RUN printf "#!/bin/bash \
\ngit clone https://github.com/GMLC-TDC/HELICS.git \
\ncd HELICS \
\nmkdir build \
\ncd build \
\ncmake .. -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_FLAGS=\"${ASAN_CFLAGS}\"  -DBUILD_HELICS_BOOST_TESTS=OFF -DZMQ_SUBPROJECT=ON  -DZMQ_FORCE_SUBPROJECT=ON \
\ncd /root/develop/HELICS/build \
\nmake -j${MAKE_PARALLEL:-2} \
\n/root/develop/HELICS/build/tests/helics/core/core-tests \
\n/root/develop/HELICS/build/tests/helics/common/common-tests \
\n/root/develop/HELICS/build/tests/helics/system_tests/system-tests \
\n" > /root/develop/buildhelics.sh
RUN chmod 775 /root/develop/buildhelics.sh

RUN ln -s /usr/bin/llvm-symbolizer-6.0 /usr/bin/llvm-symbolizer

#ENV PYTHONPATH /usr/local/python

# Python must be installed after the PYTHONPATH is set above for it to
# recognize and import libhelicsSharedLib.so.
#RUN apt install -y --no-install-recommends python3-dev \
#  && rm -rf /var/lib/apt/lists/*
