kind: pipeline
name: arm

platform:
  os: linux
  arch: arm

steps:
- name: uname
  image: alpine
  commands:
  - uname -a

- name: submodules
  image: docker:git
  commands:
  - git submodule update --init --recursive --remote

- name: build
  image: alpine
  commands:
  - apk update
  - apk add --no-cache alpine-sdk bash cmake ninja boost-dev zeromq-dev swig
  - gcc --version
  - cmake --version
  - git --version
  - mkdir build && cd build
  - cmake -GNinja -DCMAKE_BUILD_TYPE=Release ..
  - cmake --build .
  - ctest -L Continuous --output-on-failure

---
kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
- name: uname
  image: alpine
  commands:
  - uname -a

- name: submodules
  image: docker:git
  commands:
  - git submodule update --init --recursive --remote

- name: build
  image: alpine
  commands:
  - apk update
  - apk add --no-cache alpine-sdk bash cmake ninja boost-dev zeromq-dev swig
  - gcc --version
  - cmake --version
  - git --version
  - mkdir build && cd build
  - cmake -GNinja -DCMAKE_BUILD_TYPE=Release ..
  - cmake --build .
  - ctest -L Continuous --output-on-failure
