kind: pipeline
name: arm

platform:
  os: linux
  arch: arm

steps:
- name: uname
  image: alpine
  commands:
  - uname -a

- name: submodules
  image: docker:git
  commands:
  - git submodule update --init --recursive --remote

- name: build
  image: alpine
  commands:
  - apk update
  - apk add --no-cache alpine-sdk cmake boost-dev zeromq-dev swig
  - gcc --version
  - cmake --version
  - git --version
  - mkdir build && cd build
  - cmake ..
  - cmake --build . --parallel 100

---
kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
- name: uname
  image: alpine
  commands:
  - uname -a

- name: submodules
  image: docker:git
  commands:
  - git submodule update --init --recursive --remote

- name: build
  image: alpine
  commands:
  - apk update
  - apk add --no-cache alpine-sdk cmake boost-dev zeromq-dev swig
  - gcc --version
  - cmake --version
  - git --version
  - mkdir build && cd build
  - cmake ..
  - cmake --build . --parallel 100
