kind: pipeline
name: arm

platform:
  os: linux
  arch: arm

steps:
- name: uname
  image: alpine
  commands:
  - uname -a

- name: env check
  image: alpine
  commands:
  - gcc --version
  - clang --version
  - cmake --version
  - git --version

- name: build
  image: alpine
  commands:
  - apk update
  - apk add --no-cache alpine-sdk cmake boost-dev zeromq swig
  - gcc --version
  - clang --version
  - cmake --version
  - git --version

- name: env check3
  image: alpine
  commands:
  - gcc --version
  - clang --version
  - cmake --version
  - git --version

---
kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
- name: uname
  image: alpine
  commands:
  - uname -a

- name: build
  image: alpine
  commands:
  - apk update
  - apk add --no-cache alpine-sdk cmake boost-dev libzmq swig
