trigger: none
pr: none
schedules:
  - cron: '0 10 * * *'
    displayName: Daily late night PST (GMT-8)
    branches:
      include:
        - develop

jobs:
  - job: Linux
    strategy:
      matrix:
        all-tests:
          containerImage: 'helics/buildenv:ubuntu20.04-default-builder'
          test_config: 'daily'
        zmq-subproject:
          containerImage: 'helics/buildenv:ubuntu20.04-default-builder'
          test_config: 'ci'
          zmq_subproject: true
    pool:
      vmImage: 'ubuntu-latest'
    container: $[ variables['containerImage'] ]
    timeoutInMinutes: 90

    steps:
      - bash: |
          unset VCPKG_ROOT
          source scripts/setup-helics-ci-options.sh
          mkdir -p build && cd build
          ../scripts/ci-build.sh
        env:
          MAKEFLAGS: '-j 4'
          CMAKE_GENERATOR: 'Unix Makefiles'
          USE_SWIG: 'true'
          ZMQ_SUBPROJECT: $[variables['zmq_subproject']]
          ZMQ_FORCE_SUBPROJECT: $[variables['zmq_subproject']]
        displayName: 'Build HELICS'

      - bash: ../scripts/run-ci-tests.sh "$TEST_CONFIG"
        env:
          TEST_CONFIG: $[variables['test_config']]
        workingDirectory: 'build'
        displayName: 'Test HELICS'

  - job: Windows
    strategy:
      matrix:
        VS2022-64bit:
          imageName: 'windows-2022'
          langArch: 'x64'
          vsArch: 'x64'
          extraFlags: ''
    pool:
      vmImage: $(imageName)
    variables:
      BOOST_ROOT: $(Pipeline.Workspace)/ci-libs/boost
      BOOST_URL: https://sourceforge.net/projects/boost/files/boost/1.74.0/boost_1_74_0.tar.bz2/download

    steps:
      # -----------------------
      # Install dependencies
      # -----------------------
      - task: Cache@2
        inputs:
          path: $(BOOST_ROOT)
          key: boost
          cacheHitVar: BOOST_CACHE_RESTORED
        displayName: Restore Boost cache
      - bash: |
          cd $(mktemp -d)
          curl --location --output "download.tar.bz2" "$BOOST_URL"
          tar xfj "download.tar.bz2"
          mkdir -p "$BOOST_ROOT"
          cp -r boost_*/* "$BOOST_ROOT"
        condition: ne(variables.BOOST_CACHE_RESTORED, 'true')
        displayName: Install Boost
      - bash: choco install swig --yes --limit-output
        condition: eq( variables['Agent.OS'], 'Windows_NT' )
        displayName: Install swig

      # -----------------------
      # Configure HELICS
      # -----------------------
      - bash: |
          echo "BOOST_ROOT=$BOOST_ROOT"
          env
        displayName: Show environment info
      - task: CMake@1
        inputs:
          cmakeArgs: -A $(vsArch) -DHELICS_ENABLE_SWIG=ON -DHELICS_BUILD_CXX_SHARED_LIB=ON -DHELICS_ENABLE_PACKAGE_BUILD=ON -DHELICS_BUILD_TESTS=ON -DHELICS_BUILD_EXAMPLES=ON -DHELICS_DISABLE_VCPKG=ON $(extraFlags) ..
        displayName: 'Configure HELICS'
        condition: eq( variables['Agent.OS'], 'Windows_NT' )

      #  - task: CMake@1
      #    inputs:
      #      cmakeArgs: -DHELICS_BUILD_JAVA_INTERFACE=ON .
      #    displayName: 'Configure Java interface'
      #    condition: eq( variables['langArch'], 'x64' )

      # -----------------------
      # Build HELICS
      # -----------------------
      - bash: cmake --build . --config Release
        displayName: 'Build HELICS'
        workingDirectory: build

      # -----------------------
      # Package HELICS
      # -----------------------
      - bash: |
          cpack_dir="$(which cmake)"
          cpack_dir="${cpack_dir%/cmake}"
          "${cpack_dir}/cpack" -G "ZIP" -C Release -B "$PWD/installer-output"
        displayName: 'Package HELICS'
        workingDirectory: build
      - task: CopyFiles@2
        inputs:
          sourceFolder: '$(Build.SourcesDirectory)/build/installer-output'
          contents: '*.exe'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'

      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: '$(Build.ArtifactStagingDirectory)'
          artifactName: installer

      # -----------------------
      # Test HELICS
      # -----------------------
      - bash: ctest --output-on-failure --timeout 480 -C Release -L "Continuous"
        displayName: 'Test HELICS'
        workingDirectory: build

      # Packaging tests
      - bash: ctest --output-on-failure --timeout 200 -C Release -L "PackagingFast"
        displayName: 'Test HELICS packaging'
        workingDirectory: build

      # For debugging, can get build folder contents by adding PublishBuildArtifacts task and set pathtoPublish: '$(Build.SourcesDirectory)/build'
