
set(JSONCPP_WITH_TESTS OFF CACHE INTERNAL "")
set(JSONCPP_WITH_CMAKE_PACKAGE OFF CACHE INTERNAL "")
set(JSONCPP_WITH_PKGCONFIG_SUPPORT OFF CACHE INTERNAL "")
set(JSONCPP_WITH_POST_BUILD_UNITTEST OFF CACHE INTERNAL "")
set(INSTALL_EXPORT EXPORT helics-targets CACHE INTERNAL "")

if(NOT CMAKE_CXX_STANDARD)
    set(CMAKE_CXX_STANDARD 14) # Supported values are ``11``, ``14``, and ``17``.
endif()
add_subdirectory("${HELICS_SOURCE_DIR}/ThirdParty/jsoncpp" "${PROJECT_BINARY_DIR}/ThirdParty/jsoncpp")


mark_as_advanced(
JSONCPP_WITH_TESTS
JSONCPP_WITH_CMAKE_PACKAGE
JSONCPP_WITH_PKGCONFIG_SUPPORT
JSONCPP_WITH_POST_BUILD_UNITTEST
JSONCPP_USE_SECURE_MEMORY
JSONCPP_WITH_STRICT_ISO
JSONCPP_WITH_WARNING_AS_ERROR
)