compile:
	$(CC) hello_world_sender.c -o hello_world_sender -I/usr/local/Cellar/helics/HEAD-cabc611/include/helics/shared_api_library/ -lhelicsSharedLib
	$(CC) hello_world_receiver.c -o hello_world_receiver -I/usr/local/Cellar/helics/HEAD-cabc611/include/helics/shared_api_library/ -lhelicsSharedLib
