name: C/C++ CI

on: [push]

jobs:
  build:
    name: Build on os ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: |
        mkdir build 
        cd build
        cmake ..
        make
