name: Format source code

on:
  pull_request_review_comment:
    types: [created]
  issue_comment:
    types: [created]
  push:
    paths:
      - '.github/workflows/clang-format.yml'
      - '.clang-format'
      - '**.[ch]pp'
      - '**.[ch]'
      - '!ThirdParty/**'
      - '!interfaces/**'
    branches: 
      - master
      - develop

jobs:
  build:
    if: github.event_name != 'pull_request_review_comment' || contains(github.event.comment.body, '/format')
    runs-on: ubuntu-latest
    container:
      image: helics/buildenv:clang-format
    
    steps:
    - uses: actions/github-script@0.3.0
      if: github.event_name == 'issue_comment'
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.createComment({...context.issue, body: 'Okay, commit https://github.com/${{ github.repository }}/commit/${{ github.sha }} is being formatted. A PR with the changes will be open soon! :sunglasses:'})
    - uses: actions/checkout@v1
    - name: Run clang-format
      run: |
        clang-format --version
        find * | grep -v -e "^ThirdParty" -e "^interfaces" | grep -E ".*\.[ch](p{2})?$" | xargs clang-format -i -style=file
        
    - name: Stage changed source files
      shell: bash --noprofile --norc {0}
      run: |
        git diff --name-only | grep -E ".*\.[h|c](p{2})?$"
        if [[ "$?" == "0" ]];
        then
          git add *.cpp *.hpp *.c *.h
        fi
        exit 0
    - uses: ./.github/actions/create-file-update-pr
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        COMMIT_MSG: "Automated formatting of source files"
        PR_TITLE: "Automated formatting of source files"
        PR_BODY: "Automated formatting of source files in commit https://github.com/${{ github.repository }}/commit/${{ github.sha }}."
        GIT_EMAIL: "HELICS-bot@users.noreply.github.com"
        GIT_NAME: "HELICS-bot"
        BRANCH_PREFIX: "clang-format/"
