name: Code Coverage

on:
  workflow_dispatch:
  schedule:
    - cron: '15 09 * * *' # Run in the early hours of the morning (UTC)
  push:
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: coverage-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container: helics/buildenv:ubuntu26.04-default-builder
    defaults:
      run:
        shell: bash
    env:
      BUILD_TYPE: Coverage
      GCOV_TOOL: gcov
      CMAKE_GENERATOR: Unix Makefiles
      MAKEFLAGS: '-j 4'
      DISABLE_INTERFACES: 'Java'
      DISABLE_EXAMPLES: 'true'
      DISABLE_CXX_SHARED: 'true'
      
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
        submodules: recursive
      if: github.event_name != 'schedule'

    - name: Checkout develop branch
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
        submodules: recursive
        ref: develop
      if: github.event_name == 'schedule'

    - name: Build HELICS
      run: |
        unset VCPKG_ROOT
        git config --global --add safe.directory ${GITHUB_WORKSPACE}
        source scripts/setup-helics-ci-options.sh
        mkdir -p build && cd build
        ../scripts/ci-build.sh

    - name: Setup coverage counters
      working-directory: build
      run: ../scripts/lcov-helper.sh setup-counters

    - name: Run tests
      working-directory: build
      run: ../scripts/run-coverage-tests.sh

    - name: Gather coverage results
      working-directory: build
      run: ../scripts/lcov-helper.sh gather-coverage-info --gcov ${GCOV_TOOL}

    - name: Upload coverage artifact
      uses: actions/upload-artifact@v7
      with:
        if-no-files-found: error
        name: coverage-report
        path: build/coverage.info.cleaned

    - name: Upload coverage results
      uses: codecov/codecov-action@v6
      with:
        disable_search: true
        files: build/coverage.info.cleaned
        fail_ci_if_error: true
        name: coverage-ubuntu2604
        token: ${{ secrets.CODECOV_TOKEN }}
