name: docker main image

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build main docker image
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push updated Docker containers
      run: .github/actions/docker/main_docker.sh "${{ github.sha }}"
