name: Release all submodules archive

on: release

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.action == "published"
    steps:
    - uses: actions/checkout@v1
    - name: Create archive
      run: ./scripts/_git-all-archive.sh -l "$(git rev-parse --abbrev-ref "${GITHUB_REF}")"
    - name: Upload archive to release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        UPLOAD_URL: ${{ github.event.release.upload_url }}
      run: |
        AUTH_HEADER="Authorization: token ${GITHUB_TOKEN}"
        FILE="Helics-$(git rev-parse --abbrev-ref "${GITHUB_REF}").tar.gz"
        CONTENT_TYPE="$(file -b --mime-type $FILE)"
        CONTENT_LENGTH="$(stat -c%s "$FILE")"
        curl \
        -sSL \
        -XPOST \
        -H "${AUTH_HEADER}" \
        -H "Content-Length ${CONTENT_LENGTH}" \
        -H "Content-Type: ${CONTENT_TYPE}" \
        --upload-file "${FILE}" \
        "${UPLOAD_URL%\{*}?name=${FILE}"
