name: Build release artifacts

on:
  schedule:
    - cron: '15 09 * * *' # Run at in the early hours of the morning (UTC)
  release:
    types: published

jobs:
################################
# Create all submodules archive
################################
  create-all-submodule-archive:
    name: Create all submodule archive
    runs-on: ubuntu-latest
    if: github.event.action == 'published'
    steps:
    - uses: actions/checkout@v1
      
    - name: Create archive
      # Creates the archive then moves it to an artifact subfolder
      run: ./scripts/_git-all-archive.sh -l "$(git rev-parse --abbrev-ref "${GITHUB_REF}")" && mkdir artifact && mv "Helics-$(git rev-parse --abbrev-ref "${GITHUB_REF}")-source.tar.gz" artifact/
      
    - name: Upload archive to release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        UPLOAD_URL: ${{ github.event.release.upload_url }}
      run: ./.github/workflows/upload-release-asset.sh "artifact/Helics-$(git rev-parse --abbrev-ref "${GITHUB_REF}")-source.tar.gz"
      
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: all-submodules-archive
        path: artifact
        
################################
# Build MSVC archives
################################
  build-windows-msvc:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2016, windows-latest]
        arch: [x64]
        include:
          - os: windows-2016
            cmake_gen: 'Visual Studio 15 2017'
            msvc_ver: 'msvc2017'
          - os: windows-latest
            cmake_gen: 'Visual Studio 16 2019'
            msvc_ver: 'msvc2019'
    steps:
    - name: Checkout event ref
      uses: actions/checkout@v1
      if: github.event.action == 'published'
    
    - name: Checkout develop branch
      uses: actions/checkout@v1
      with:
        ref: develop
      if: github.event_name == 'schedule'
      
    # Build with Python 3.6 interface
    - uses: actions/setup-python@v1
      with:
        python-version: '3.6'
        architecture: ${{ matrix.arch }}
        
    # Compile HELICS and create the installer
    - name: Build installer
      env:
        BUILD_ARCH: ${{ matrix.arch }}
        BUILD_GEN: ${{ matrix.cmake_gen }}
        MSVC_VER: ${{ matrix.msvc_ver }}
      shell: bash
      # This uses bash variable substitution in a few places
      # 1. replacing x86 with Win32 (setting the Python version uses x86)
      # 2. getting the cmake directory for running cpack with an absolute path (chocolatey has an unfortunately named alias)
      # 3. moving the generated installer with a rename to add msvcYYYY to the file name
      run: |
        echo "Building with ${BUILD_GEN} for ${BUILD_ARCH}"
        choco install -y swig
        cpack_dir="$(which cmake)"
        cpack_dir="${cpack_dir%/cmake}"
        mkdir build && cd build
        cmake -G "${BUILD_GEN}" -A "${BUILD_ARCH/x86/Win32}" -DCMAKE_BUILD_TYPE=Debug -DHELICS_ENABLE_PACKAGE_BUILD=ON -DHELICS_BUILD_CXX_SHARED_LIB=ON -DHELICS_BUILD_EXAMPLES=OFF -DBUILD_TESTING=OFF -DHELICS_BUILD_APP_EXECUTABLES=OFF -DHELICS_BUILD_APP_LIBRARY=ON -DHELICS_DISABLE_C_SHARED_LIB=ON ..
        cmake --build . --config Debug
        echo "Packing Debug"
        "${cpack_dir}/cpack" -G "ZIP" -C Debug -B "$(pwd)/../tmp_dir"
        pushd ../tmp_dir
        rm -rf _CPack_Packages
        ZIP_FILE="$(ls Helics-*.zip)"
        7z x "$ZIP_FILE" -y
        rm "$ZIP_FILE"
        popd
        cmake -G "${BUILD_GEN}" -A "${BUILD_ARCH/x86/Win32}" -DCMAKE_BUILD_TYPE=Release -DHELICS_ENABLE_PACKAGE_BUILD=ON -DHELICS_BUILD_CXX_SHARED_LIB=ON -DHELICS_BUILD_EXAMPLES=OFF -DBUILD_TESTING=OFF -DHELICS_BUILD_APP_EXECUTABLES=OFF -DHELICS_BUILD_APP_LIBRARY=ON -DHELICS_DISABLE_C_SHARED_LIB=ON ..
        cmake --build . --config Release
        echo "Packing Release"
        "${cpack_dir}/cpack" -G "ZIP" -C Release -B "$(pwd)/../tmp_dir"
        cd ../tmp_dir
        rm -rf _CPack_Packages
        ZIP_FILE="$(ls Helics-*.zip)"
        7z x "$ZIP_FILE" -y
        rm "$ZIP_FILE"
        7z a "$ZIP_FILE" -r *
        mkdir ../artifact
        mv "$ZIP_FILE" "../artifact/${ZIP_FILE/-win/-${MSVC_VER}-win}"
        
    - name: Upload installer to release
      if: github.event.action == 'published'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        UPLOAD_URL: ${{ github.event.release.upload_url }}
      shell: bash
      run: ./.github/workflows/upload-release-asset.sh "$(ls artifact/Helics-*.zip)"
      
    # GitHub Actions combines artifacts uploaded with the same name
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: windows-installers
        path: artifact
        
################################
# Build Windows installer
################################
  build-windows-installer:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        arch: [x64]
        cpack_gen: [NSIS, ZIP]
        include:
          - os: windows-latest
            cmake_gen: 'Visual Studio 16 2019'
            msvc_ver: 'msvc2019'
    steps:
    - name: Checkout event ref
      uses: actions/checkout@v1
      if: github.event.action == 'published'
    
    - name: Checkout develop branch
      uses: actions/checkout@v1
      with:
        ref: develop
      if: github.event_name == 'schedule'
      
    # Build with Python 3.6 interface
    - uses: actions/setup-python@v1
      with:
        python-version: '3.6'
        architecture: ${{ matrix.arch }}
        
    # Compile HELICS and create the installer
    - name: Build installer
      env:
        BUILD_ARCH: ${{ matrix.arch }}
        BUILD_GEN: ${{ matrix.cmake_gen }}
        MSVC_VER: ${{ matrix.msvc_ver }}
        CPACK_GEN: ${{ matrix.cpack_gen }}
      shell: bash
      # This uses bash variable substitution in a few places
      # 1. replacing x86 with Win32 (setting the Python version uses x86)
      # 2. getting the cmake directory for running cpack with an absolute path (chocolatey has an unfortunately named alias)
      run: |
        echo "Building ${CPACK_GEN} installer with ${BUILD_GEN} for ${BUILD_ARCH}"
        choco install -y swig
        mkdir build && cd build
        cmake -G "${BUILD_GEN}" -A "${BUILD_ARCH/x86/Win32}" -DCMAKE_BUILD_TYPE=Release -DHELICS_ENABLE_PACKAGE_BUILD=ON -DBUILD_PYTHON_INTERFACE=ON -DBUILD_JAVA_INTERFACE=ON -DSTATIC_STANDARD_LIB=ON -DHELICS_BUILD_EXAMPLES=OFF -DHELICS_BUILD_APP_EXECUTABLES=ON -DHELICS_BUILD_APP_LIBRARY=OFF -DBUILD_TESTING=OFF .. || true
        cmake --build . --config Release
        cpack_dir="$(which cmake)"
        cpack_dir="${cpack_dir%/cmake}"
        "${cpack_dir}/cpack" -G "${CPACK_GEN}" -C Release -B "$(pwd)/../artifact"
        cd ../artifact
        rm -rf _CPack_Packages
        
    - name: Upload installer to release
      if: github.event.action == 'published'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        UPLOAD_URL: ${{ github.event.release.upload_url }}
      shell: bash
      run: ./.github/workflows/upload-release-asset.sh "$(ls artifact/Helics-*)"
      
    # GitHub Actions combines artifacts uploaded with the same name
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: windows-installers
        path: artifact
        
################################
# Build Windows shared library
################################
  build-windows-sharedlib:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        arch: [x64, x86]
        include:
          - os: windows-latest
            cmake_gen: 'Visual Studio 16 2019'
            msvc_ver: 'msvc2019'
    steps:
    - name: Checkout event ref
      uses: actions/checkout@v1
      if: github.event.action == 'published'
    
    - name: Checkout develop branch
      uses: actions/checkout@v1
      with:
        ref: develop
      if: github.event_name == 'schedule'
        
    # Compile HELICS and create the installer
    - name: Build installer
      env:
        BUILD_ARCH: ${{ matrix.arch }}
        BUILD_GEN: ${{ matrix.cmake_gen }}
        MSVC_VER: ${{ matrix.msvc_ver }}
      shell: bash
      # This uses bash variable substitution in a few places
      # 1. replacing x86 with Win32 (setting the Python version uses x86)
      # 2. getting the cmake directory for running cpack with an absolute path (chocolatey has an unfortunately named alias)
      run: |
        echo "Building shared library with ${BUILD_GEN} for ${BUILD_ARCH}"
        choco install -y swig
        mkdir build && cd build
        cmake -G "${BUILD_GEN}" -A "${BUILD_ARCH/x86/Win32}" -DCMAKE_BUILD_TYPE=Release -DHELICS_ENABLE_PACKAGE_BUILD=ON -DSTATIC_STANDARD_LIB=ON -DHELICS_BUILD_APP_EXECUTABLES=OFF -DHELICS_BUILD_APP_LIBRARY=OFF -DHELICS_BUILD_EXAMPLES=OFF -DBUILD_TESTING=OFF .. || true
        cmake --build . --config Release
        cpack_dir="$(which cmake)"
        cpack_dir="${cpack_dir%/cmake}"
        "${cpack_dir}/cpack" -G "TGZ" -C Release -B "$(pwd)/../artifact"
        cd ../artifact
        rm -rf _CPack_Packages
        ARCHIVE_FILE="$(ls Helics-*)"
        mv "$ARCHIVE_FILE" "${ARCHIVE_FILE/Helics-/Helics-shared-}"
        
    - name: Upload installer to release
      if: github.event.action == 'published'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        UPLOAD_URL: ${{ github.event.release.upload_url }}
      shell: bash
      run: ./.github/workflows/upload-release-asset.sh "$(ls artifact/Helics-*)"
      
    # GitHub Actions combines artifacts uploaded with the same name
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: windows-installers
        path: artifact
      
################################
# Build macOS installer
################################
  build-macos-installer:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
    - name: Checkout event ref
      uses: actions/checkout@v1
      if: github.event.action == 'published'
    
    - name: Checkout develop branch
      uses: actions/checkout@v1
      with:
        ref: develop
      if: github.event_name == 'schedule'
        
    # Build with Python 3.6 interface
    - uses: actions/setup-python@v1
      with:
        python-version: '3.6'
        
    # Compile HELICS and create the installer
    - name: Build installer
      shell: bash
      # This uses bash variable substitution in a few places
      # 1. getting the cmake directory for running cpack with an absolute path (chocolatey has an unfortunately named alias)
      run: |
        brew install swig boost
        mkdir build && cd build
        cmake -DCMAKE_BUILD_TYPE=Release -DHELICS_ZMQ_SUBPROJECT=ON -DHELICS_ENABLE_PACKAGE_BUILD=ON -DBUILD_PYTHON_INTERFACE=ON -DBUILD_JAVA_INTERFACE=ON -DHELICS_BUILD_EXAMPLES=OFF -DHELICS_BUILD_APP_EXECUTABLES=ON -DHELICS_BUILD_APP_LIBRARY=OFF -DBUILD_TESTING=OFF .. || true
        cmake --build . --config Release
        cpack_dir="$(which cmake)"
        cpack_dir="${cpack_dir%/cmake}"
        "${cpack_dir}/cpack" -G "TGZ" -C Release -B "$(pwd)/../artifact"
        cd ../artifact
        rm -rf _CPack_Packages
        
    - name: Upload installer to release
      if: github.event.action == 'published'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        UPLOAD_URL: ${{ github.event.release.upload_url }}
      shell: bash
      run: ./.github/workflows/upload-release-asset.sh "$(ls artifact/Helics-*)"
      
    # GitHub Actions combines artifacts uploaded with the same name
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: macos-installers
        path: artifact
      
################################
# Build macOS shared library
################################
  build-macos-sharedlib:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
    - name: Checkout event ref
      uses: actions/checkout@v1
      if: github.event.action == 'published'
    
    - name: Checkout develop branch
      uses: actions/checkout@v1
      with:
        ref: develop
      if: github.event_name == 'schedule'
        
    # Compile HELICS and create the installer
    - name: Build installer
      shell: bash
      # This uses bash variable substitution in a few places
      # 1. getting the cmake directory for running cpack with an absolute path (chocolatey has an unfortunately named alias)
      run: |
        brew install swig boost
        mkdir build && cd build
        cmake -DCMAKE_BUILD_TYPE=Release -DHELICS_ZMQ_SUBPROJECT=ON -DHELICS_ENABLE_PACKAGE_BUILD=ON -DHELICS_BUILD_APP_EXECUTABLES=OFF -DHELICS_BUILD_APP_LIBRARY=OFF -DHELICS_BUILD_EXAMPLES=OFF -DBUILD_TESTING=OFF .. || true
        cmake --build . --config Release
        cpack_dir="$(which cmake)"
        cpack_dir="${cpack_dir%/cmake}"
        "${cpack_dir}/cpack" -G "TGZ" -C Release -B "$(pwd)/../artifact"
        cd ../artifact
        rm -rf _CPack_Packages
        ARCHIVE_FILE="$(ls Helics-*)"
        mv "$ARCHIVE_FILE" "${ARCHIVE_FILE/Helics-/Helics-shared-}"
        
    - name: Upload installer to release
      if: github.event.action == 'published'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        UPLOAD_URL: ${{ github.event.release.upload_url }}
      shell: bash
      run: ./.github/workflows/upload-release-asset.sh "$(ls artifact/Helics-*)"
      
    # GitHub Actions combines artifacts uploaded with the same name
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: macos-installers
        path: artifact
        
################################
# Build Linux shared library
################################
  build-linux-sharedlib:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - name: Checkout event ref
      uses: actions/checkout@v1
      if: github.event.action == 'published'
    
    - name: Checkout develop branch
      uses: actions/checkout@v1
      with:
        ref: develop
      if: github.event_name == 'schedule'
        
    # Compile HELICS and create the installer
    - name: Build installer
      shell: bash
      # This uses bash variable substitution in a few places
      # 1. getting the cmake directory for running cpack with an absolute path (chocolatey has an unfortunately named alias)
      run: |
        sudo apt-get install -y libboost-dev
        mkdir build && cd build
        cmake -DCMAKE_BUILD_TYPE=Release -DHELICS_ZMQ_SUBPROJECT=ON -DHELICS_ENABLE_PACKAGE_BUILD=ON -DSTATIC_STANDARD_LIB=ON -DHELICS_BUILD_APP_EXECUTABLES=OFF -DHELICS_BUILD_APP_LIBRARY=OFF -DHELICS_BUILD_EXAMPLES=OFF -DBUILD_TESTING=OFF .. || true
        cmake --build . --config Release
        cpack_dir="$(which cmake)"
        cpack_dir="${cpack_dir%/cmake}"
        "${cpack_dir}/cpack" -G "TGZ" -C Release -B "$(pwd)/../artifact"
        cd ../artifact
        rm -rf _CPack_Packages
        ARCHIVE_FILE="$(ls Helics-*)"
        mv "$ARCHIVE_FILE" "${ARCHIVE_FILE/Helics-/Helics-shared-}"
        
    - name: Upload installer to release
      if: github.event.action == 'published'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        UPLOAD_URL: ${{ github.event.release.upload_url }}
      shell: bash
      run: ./.github/workflows/upload-release-asset.sh "$(ls artifact/Helics-*)"
      
    # GitHub Actions combines artifacts uploaded with the same name
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: linux-installers
        path: artifact
      
################################
# Generate SHA-256 file
################################
  generate-sha256:
    name: Calculate SHA256 for release assets
    needs: [create-all-submodule-archive, build-windows-installer, build-windows-msvc, build-windows-sharedlib, build-macos-installer, build-macos-sharedlib, build-linux-sharedlib]
    runs-on: ubuntu-latest
    if: github.event.action == 'published'
    steps:
    - uses: actions/checkout@v1
      
    - name: Get all submodules archive
      uses: actions/download-artifact@v1
      with:
        name: all-submodules-archive
        path: artifacts
        
    - name: Get Windows installers
      uses: actions/download-artifact@v1
      with:
        name: windows-installers
        path: artifacts
        
    - name: Get macOS installers
      uses: actions/download-artifact@v1
      with:
        name: macos-installers
        path: artifacts
        
    - name: Get Linux installers
      uses: actions/download-artifact@v1
      with:
        name: linux-installers
        path: artifacts
        
    - name: Create SHA-256 file
      run: cd artifacts && sha256sum * > "Helics-$(git rev-parse --abbrev-ref "${GITHUB_REF}")-SHA-256.txt"
      
    - name: Upload SHA-256 file to release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        UPLOAD_URL: ${{ github.event.release.upload_url }}
      run: ./.github/workflows/upload-release-asset.sh "artifacts/Helics-$(git rev-parse --abbrev-ref "${GITHUB_REF}")-SHA-256.txt"
