name: Release all submodules archive

on: release

jobs:
  create-all-submodule-archive:
    name: Create all submodule archive
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      if: github.event.action == 'published'
    - name: Create archive
      if: github.event.action == 'published'
      # Creates the archive then moves it to an artifact subfolder
      run: ./scripts/_git-all-archive.sh -l "$(git rev-parse --abbrev-ref "${GITHUB_REF}")" && mkdir artifact && mv "Helics-$(git rev-parse --abbrev-ref "${GITHUB_REF}").tar.gz" artifact/
    - name: Upload archive to release
      if: github.event.action == 'published'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        UPLOAD_URL: ${{ github.event.release.upload_url }}
      run: ./.github/workflows/upload-release-asset.sh "artifact/Helics-$(git rev-parse --abbrev-ref "${GITHUB_REF}").tar.gz"
    - name: Upload artifact
      if: github.event.action == 'published'
      uses: actions/upload-artifact@v1
      with:
        name: all-submodules-archive
        path: artifact
        
  build-windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2016, windows-2019]
        arch: [x86, x64]
        include:
          - os: windows-2016
            cmake_gen: 'Visual Studio 15 2017'
            msvc_ver: 'msvc2017'
          - os: windows-2019
            cmake_gen: 'Visual Studio 16 2019'
            msvc_ver: 'msvc2019'
    steps:
    - uses: actions/checkout@v1
      if: github.event.action == 'published'
    - uses: actions/setup-python@v1
      if: github.event.action == 'published'
      with:
        python-version: '3.7'
        architecture: ${{ matrix.arch }}
    - name: Build installer
      if: github.event.action == 'published'
      env:
        BUILD_ARCH: ${{ matrix.arch }}
        BUILD_GEN: ${{ matrix.cmake_gen }}
        MSVC_VER: ${{ matrix.msvc_ver }}
      run: |
        echo "Building with ${BUILD_GEN} for ${BUILD_ARCH}"
        # Run CMake with Win32 instead of x86
        #python -m pip install --upgrade pip
        #choco install -y swig
        mkdir artifact
        touch artifact/test-${BUILD_GEN}-${MSVC_VER}-${BUILD_ARCH}
    - name: Upload artifact
      if: github.event.action == 'published'
      uses: actions/upload-artifact@v1
      with:
        name: windows-installers
        path: artifact
        
  generate-sha256:
    name: Calculate SHA256 for release assets
    needs: [create-all-submodule-archive, build-windows]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      if: github.event.action == 'published'
    - name: Get all submodules archive
      if: github.event.action == 'published'
      uses: actions/download-artifact@v1
      with:
        name: all-submodules-archive
        path: artifacts
    - name: Get Windows installers
      if: github.event.action == 'published'
      uses: actions/download-artifact@v1
      with:
        name: windows-installers
        path: artifacts
    - name: Print some info on fetched artifacts
      if: github.event.action == 'published'
      run: sha256sum * > "Helics-$(git rev-parse --abbrev-ref "${GITHUB_REF}")-SHA-256.txt"
    - name: Upload SHA-256 file to release
      if: github.event.action == 'published'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        UPLOAD_URL: ${{ github.event.release.upload_url }}
      run: ./.github/workflows/upload-release-asset.sh "artifacts/Helics-$(git rev-parse --abbrev-ref "${GITHUB_REF}")-SHA-256.txt"
